name: pack & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: pack
      run: dotnet pack src/JobBot.Common/JobBot.Common.Models/JobBot.Common.Models.csproj --configuration Release
    - name: publish
      run: dotnet nuget push "src/JobBot.Common/JobBot.Common.Models/bin/Release/JobBot.Common.Models.1.0.0.nupkg" --source "github"