name: pack & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: add source
      run: dotnet nuget add source https://nuget.pkg.github.com/DmytroSH/index.json --name "JobBot.Common.Models" -u DmytroSH -p ${{ secrets.GITHUB_TOKEN }}
    - name: pack
      run: dotnet pack src/JobBot.Common/JobBot.Common.Models/JobBot.Common.Models.csproj --configuration Release
    - name: publish
      run: dotnet nuget push "src/JobBot.Common/JobBot.Common.Models/bin/Release/JobBot.Common.Models.1.0.0.nupkg" --source "JobBot.Common.Models"